#!/bin/sh
xrandr --output HDMI-0 --primary

bspc monitor HDMI-0 -d I II III IV V

bspc config border_width 1
bspc config window_gap   4

bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config normal_border_color  \#3c3836
bspc config focused_border_color \#a49db9

bspc config click_to_focus false
bspc config focus_follows_pointer on

#AUTOSTART
redshift -l 39:21 -t 6500:3500 &
unclutter &
sxhkd &
lxpolkit &
ulauncher --hide-window --no-window-shadow &
dunst &

setxkbmap -option grp:rctrl_rshift_toggle us,gr &

~/.config/ui-update.sh &
