#!/bin/zsh

pgrep -x sxhkd > /dev/null || sxkhd &

bspc config border_width 4
bspc config window_gap   6

bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config normal_border_color  "#3C3836"
bspc config focused_border_color "#A49DB9"
bspc config active_border_color  "#A49DB9"

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true

~/.config/bspwm/layout.sh
~/.config/bspwm/autostart.sh
